from invenio_records_resources.records.api import FileRecord
from invenio_records_resources.services.files.processors.base import FileProcessor

class ImageMetadataExtractor(FileProcessor):
    def can_process(self, file_record: FileRecord) -> bool: ...
    def process(self, file_record: FileRecord) -> None: ...
