from __future__ import annotations

from typing import Any

def on_block(user_id: str | int, uow: Any | None = ..., **kwargs: Any) -> None: ...
def on_restore(user_id: str | int, uow: Any | None = ..., **kwargs: Any) -> None: ...
def on_approve(user_id: str | int, uow: Any | None = ..., **kwargs: Any) -> None: ...
