from abc import ABC, abstractmethod
from typing import (
    Any,
    Callable,
    Optional,
)

from invenio_records_resources.records.api import Record
from marshmallow.fields import Field

def ensure_no_field_cls(func: Callable) -> Callable: ...

class BaseCF(ABC):
    name: str
    def __init__(self, name: str, field_args: Optional[Any] = ...): ...
    @property
    @abstractmethod
    def mapping(self) -> Any: ...
    @property
    @abstractmethod
    def field(self) -> Field: ...
    @property
    def ui_field(self) -> Field: ...
    def dump(self, record: Record, cf_key: str = ...): ...
    def load(self, record: Record, cf_key: str = ...): ...

class BaseListCF(BaseCF):
    def __init__(self, name: str, field_cls: Any, multiple: bool = ..., **kwargs): ...
    @property
    def field(self) -> Field: ...
    @property
    @abstractmethod
    def mapping(self) -> Any: ...
