from typing import Any, Dict

class BooleanMapping:
    def to_dict(self) -> Dict[str, str]: ...

class DoubleMapping:
    def to_dict(self) -> Dict[str, str]: ...

class EDTFMapping:
    def to_dict(self) -> Dict[str, Any]: ...

class ISODateMapping:
    def to_dict(self) -> Dict[str, str]: ...

class IntegerMapping:
    def to_dict(self) -> Dict[str, str]: ...

class KeywordMapping:
    def to_dict(self) -> Dict[str, str]: ...

class TextMapping:
    def __init__(self, use_as_filter: bool = ...): ...
    def to_dict(self) -> Dict[str, Any]: ...
