from typing import Dict


class DoubleCF:
    def __init__(self, name: str, **kwargs): ...
    @property
    def mapping(self) -> Dict[str, str]: ...


class IntegerCF:
    def __init__(self, name: str, **kwargs): ...
    @property
    def mapping(self) -> Dict[str, str]: ...
