from typing import Any, Dict

class CustomFieldsSchema:
    def __init__(self, fields_var: str, *args, **kwargs): ...
    def _deserialize(self, data: Dict[str, Any], **kwargs) -> Dict[str, Any]: ...
