from .fixtures.demo import create_fake_community as create_fake_community
from .fixtures.tasks import create_demo_community as create_demo_community
from .proxies import current_communities as current_communities, current_identities_cache as current_identities_cache
from flask.cli import with_appcontext

def communities() -> None: ...
def identity_cache() -> None: ...
@with_appcontext
def clear() -> None: ...
@with_appcontext
def demo() -> None: ...
@with_appcontext
def rebuild_index() -> None: ...
def custom_fields() -> None: ...
@with_appcontext
def create_communities_custom_field(field_name) -> None: ...
@with_appcontext
def custom_field_exists_in_communities(field_name) -> None: ...
