from typing import Optional


class Pagination:
    def __init__(self, size: int, page: int, max_results: int): ...
    @property
    def from_idx(self) -> int: ...
    @property
    def has_next(self) -> bool: ...
    @property
    def has_prev(self) -> bool: ...
    @property
    def next_page(self) -> Optional[Pagination]: ...
    @property
    def prev_page(self) -> Optional[Pagination]: ...
    @property
    def to_idx(self) -> int: ...
    def valid(self) -> bool: ...
