from typing import Callable, List, Optional

from invenio_records_resources.services.base import Service

class ServiceRegistry:
    def __init__(self) -> None: ...
    def register(
        self, service_instance: Service, service_id: Optional[str] = ...
    ) -> None: ...
    def get(self, service_id: str) -> Service: ...
    def get_service_id(self, instance: Service) -> str: ...

class NotificationRegistry:
    def __init__(self) -> None: ...
    def register(self, record_type: str, handler: Callable) -> None: ...
    def get(self, record_type: str) -> List[Callable]: ...
