from typing import Any, Callable, Dict, List, Optional

from invenio_records_resources.services.base import Service

class ServiceRegistry:
    _services: Dict[str, Service]

    def __init__(self) -> None: ...
    def register(
        self, service_instance: Service, service_id: Optional[str] = ...
    ) -> None: ...
    def get(self, service_id: str) -> Service: ...
    def get_service_id(self, instance: Service) -> str: ...

class NotificationRegistry:
    _handlers: Dict[str, List[Callable[..., Any]]]

    def __init__(self) -> None: ...
    def register(self, record_type: str, handler: Callable[..., Any]) -> None: ...
    def get(self, record_type: str) -> List[Callable[..., Any]]: ...
