from flask import Blueprint

blueprint: Blueprint

def create_blueprint_from_app(app): ...
def create_affiliations_blueprint_from_app(app): ...
def create_awards_blueprint_from_app(app): ...
def create_funders_blueprint_from_app(app): ...
def create_names_blueprint_from_app(app): ...
def create_subjects_blueprint_from_app(app): ...
def create_list_blueprint_from_app(app): ...
