from invenio_records.systemfields import SystemField
from invenio_records_resources.references.entity_resolvers import (
    EntityProxy as EntityProxy,
)

class ReferencedEntityField(SystemField):
    def __init__(
        self, key=None, reference_check_func=None, resolver_registry=None
    ) -> None: ...
    def set_obj(self, instance, obj) -> None: ...
    def obj(self, instance): ...

class MultiReferenceEntityField(ReferencedEntityField):
    def set_obj(self, instance, objs) -> None: ...
    def obj(self, instance): ...

def check_allowed_references(get_allows_none, get_allowed_types, request, ref_dict): ...
