from _typeshed import Incomplete
from flask_resources.errors import HTTPJSONException
from invenio_pidstore.errors import PIDDoesNotExistError

class RedirectException(HTTPJSONException):
    code: int
    location: Incomplete
    def __init__(self, location, **kwargs) -> None: ...
    def get_headers(self, environ=None, scope=None): ...
    def get_body(self, environ=None, scope=None): ...

class DraftNotCreatedError(PIDDoesNotExistError): ...
