from .tasks import delete_community as delete_community, restore_community as restore_community
from invenio_communities.proxies import current_communities as current_communities

def on_block(user_id, uow=None, **kwargs) -> None: ...
def on_restore(user_id, uow=None, **kwargs) -> None: ...
def on_approve(user_id, uow=None, **kwargs) -> None: ...
