from invenio_communities.errors import DeletionStatusError as DeletionStatusError
from invenio_communities.proxies import current_communities as current_communities

def delete_community(community_id, tombstone_data) -> None: ...
def restore_community(community_id) -> None: ...
