from collections.abc import Iterator, Mapping
from typing import Any, Dict

from invenio_records.systemfields import SystemField
from invenio_records_resources.records.api import FileRecord

class TransferFieldData(Mapping[str, Any]):
    def __init__(self, field: Dict[str, Any]) -> None: ...
    @property
    def transfer_type(self) -> Any: ...
    @transfer_type.setter
    def transfer_type(self, value: Any) -> None: ...
    def get(self, key: str, default: Any = ...) -> Any: ...
    def set(self, values: Dict[str, Any]) -> None: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __iter__(self) -> Iterator[str]: ...
    def __len__(self) -> int: ...

class TransferField(SystemField[FileRecord, TransferFieldData]): ...
