from typing import Any, Dict, Optional, Type

from invenio_records_resources.records.api import FileRecord

class TransferField:
    def __get__(
        self, record: FileRecord, owner: Optional[Type[FileRecord]] = ...
    ) -> TransferFieldData: ...
    def __set__(self, record: FileRecord, value: Dict[str, Any]): ...

class TransferFieldData:
    def __getitem__(self, key: str) -> Dict[str, Any]: ...
    def __init__(
        self,
        field: Dict[str, Any],
    ): ...
    def __setitem__(self, key: str, value: Dict[str, Any]): ...
    def get(self, key: str, default: Optional[str] = ...) -> Optional[str]: ...
    def set(self, values: Dict[str, str]): ...
