from typing import Any

import click  # type: ignore[import-untyped]

def abort_if_false(ctx: click.Context, param: Any, value: Any) -> None: ...
def render_url(url: str) -> str: ...
def db(*args: Any, **kwargs: Any) -> Any: ...
def create(*args: Any, **kwargs: Any) -> Any: ...
def drop(*args: Any, **kwargs: Any) -> Any: ...
def init(*args: Any, **kwargs: Any) -> Any: ...
def destroy(*args: Any, **kwargs: Any) -> Any: ...
