from typing import (
    Any,
    Callable,
    Dict,
    Union,
)

from invenio_db.shared import db as _db
from sqlalchemy.engine.base import Engine  # type: ignore

def alembic_test_context() -> Dict[str, Union[bool, Callable[..., Any]]]: ...
def create_alembic_version_table() -> None: ...
def drop_alembic_version_table() -> None: ...
def has_table(engine: Engine, table: str) -> bool: ...
def versioning_models_registered(manager: Any, base: Any) -> bool: ...
def versioning_model_classname(manager: Any, model: Any) -> str: ...
def rebuild_encrypted_properties(
    old_key: Any, model: Any, properties: Any, db: Any = _db
) -> None: ...
