from typing import Any, Generator, Self

from invenio_search.engine import dsl

class FacetsResponse(dsl.response.Response):  # type: ignore[misc]
    @classmethod
    def create_response_cls(cls, facets_param: Any) -> type[Self]: ...
    def _iter_facets(self) -> Generator[tuple[str, Any, Any, Any], None, None]: ...
    @property
    def facets(self) -> dsl.AttrDict: ...
    @property
    def labelled_facets(self) -> dsl.AttrDict: ...
