from invenio_records_resources.services.uow import RecordCommitOp

class ParentRecordCommitOp(RecordCommitOp):
    def __init__(self, parent, indexer_context=None, bulk_index: bool = True) -> None: ...
    def on_commit(self, uow) -> None: ...
    def on_post_commit(self, uow) -> None: ...
